### ISSUE TITLE
New ZMQ version kernel does not start

### ISSUE THREAD

**Issue by dietmarw** [OpenModelica/jupyter-openmodelica#6]
I'm getting the following error message: 
    
    File "/opt/conda/lib/python3.6/site-packages/openmodelica_kernel/kernel.py", line 39, in <module>
    reload(sys)
    NameError: name 'reload' is not defined

**Comment by bilderbuchi** [comment]
Not at a PC right now, but afaik, reload moved into the imp module or some such in py3. I think there's a section on the futurize webpage on how to do this in a py2/py3 compatible way.

**Comment by arun3688** [comment]
@dietmarw  The reload module is adapted to both Python 2and  Python 3 versions, can you check whether it works for you

**Comment by dietmarw** [comment]
Unfortunately not:

    File "/opt/conda/lib/python3.6/site-packages/openmodelica_kernel/kernel.py", line 49, in <module>
    sys.setdefaultencoding("utf-8")
    AttributeError: module 'sys' has no attribute 'setdefaultencoding'

I'm pretty sure that python 3 no longer needs the encoding set since everything is utf8 IIRC

**Comment by hchesser** [comment]
I am also having this issue with OpenModelica 1.12.0-dev installed, Windows 10, 64-bit, Python 3.5, Anaconda3.

AttributeError: module 'sys' has no attribute 'setdefaultencoding'

Is there a solution for this?

**Comment by hchesser** [comment]
I commented out the offending line (49) in kernel.py, then open the example OpenModelica.ipynb.  I execute the first cell:

[W 20:10:20.351 NotebookApp] 404 GET /static/components/codemirror/mode/openmodelica/openmodelica.js?v=20170803201011 (::1) 10.19ms referer=http://localhost:8891/notebooks/OpenModelica.ipynb
2017-08-03 20:10:21,380 - OMPython - INFO - OMC Server is up and running at file:///C:/Users/chesser/AppData/Local/Temp/openmodelica.port.b78f7a531f444b89ab9f6e9d7e53aec7
[IPKernelApp] WARNING | Unknown message type: 'comm_open'
[IPKernelApp] WARNING | Unknown message type: 'comm_open'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "C:\Users\chesser\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\Users\chesser\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "C:\Users\chesser\Anaconda3\lib\site-packages\openmodelica_kernel\kernel.py", line 137, in do_execute
    plotcommand=z1.replace(' ','').startswith('plot(')and z1.replace(' ','').endswith(')')
AttributeError: 'filter' object has no attribute 'replace'

**Comment by hchesser** [comment]
The above issue is a separate one (Python 2/3 syntax).  The resolution to the original issue appears to be to comment out line 49 in kernel.py.

**Comment by arun3688** [comment]
@hchesser I am fixing the code to work with Python 3, However the code fully works on Python 2, So hopefully i will fix it as early as possible

**Comment by arun3688** [comment]
@dietmarw @hchesser , The issues are fixed now,  i tested with both Python 2 and Python 3 version, it works, You can pull the latest code and test it

**Comment by dietmarw** [comment]
@arun3688 Could you specify "now" a bit more in detail. Which commit was fixing it?

**Comment by dietmarw** [comment]
I can confirm it runs under Python 3 after 1e5496f16e8e9fd44965131b5ef8705ce751c3ac

**Comment by arun3688** [comment]
@dietmarw , that commit fixes both Python 3 and Python 2 as well as

**Comment by arun3688** [comment]
@dietmarw  I hope everything works now, i can close this issue

**Comment by dietmarw** [comment]
As I said I could only test it for Python 3. If you are certain that it does work on Python 2 then this can be closed.

**Comment by arun3688** [comment]
ok I tested with Python2 as well, So i close this

**Comment by hchesser** [comment]
I confirm it works now for the OpenModelica.ipynb example.  Thanks!
