### ISSUE TITLE
Numpy dependency not recorded

### ISSUE THREAD

**Issue by bilderbuchi** [OpenModelica/jupyter-openmodelica#8]
This is a really bite-sized issue. The dependency on numpy is not reflected in setup.py's `install_requires`. 

At the same time a dependency on OMPython should be added. Here, a minimum OMPython could maybe be set such that the requirement of OpenModelica >1.12.0 (see #5) could be codified in that way (since OMPython comes with Openmodelica, right?)

**Comment by sjoelund** [comment]
No, OMPython is totally separate from OpenModelica. We install OMPython using `pip` at least on Linux and OSX.

**Comment by thorade** [comment]
Jupyter is also required and available on PyPI.
https://pypi.python.org/pypi/jupyter
